### ISSUE TITLE
Dont trash user home with dotfiles…

### ISSUE THREAD

**Issue by Tokariew** [igroglaz/Tangaria#85]
User home is not place for dotfiles… If possible use [XDG Base Directory](https://wiki.archlinux.org/title/XDG_Base_Directory)
In tomenet I can move .tomenetrc and lib Path with switches like so
```
/home/tokariew/gits/mine/tomenet/tomenet -f/home/tokariew/.local/share/tomenet/.tomenetrc -P/home/tokariew/.local/share/tomenet -e -V
```
i hardcoded only because i'm lazy…

**Comment by s88100** [comment]
'.pwmangrc' to get path to config file `./pwmangclient --config /path/file`
to change directory for storing pref-files and character-dumps.
`./configure CFLAGS=-DPRIVATE_USER_PATH=\\\"~/.pwmangband\\\"`

**Comment by s88100** [comment]
/src/client/conf.c
`conf_init()`
  _Try to find home directory. Otherwise use current directory._

if change the current working directory `cd /path`
and run `./pwmangclient` then '.pwmangrc' file will be created in current directory, if file is not in home ~/.pwmangrc

PWMAngband/configure.ac
--with-private-dirs  _This configures the game to store savefiles and scorefiles for each user
in that user's home directory. This is enabled by default._

> var path:    (not used)
> (with private save and score files in ~/.pwmangband/PWMAngband/)

in V  Handle a `"-d<dir>=<path>"` option.
Sets any of angband's special directories to <path>.
angband-4.2.3/src/main.c
`change_path()`
